// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Generate does not connect to the DB; a placeholder is enough when DATABASE_URL is unset at build time.
    url: process.env["DATABASE_URL"] ?? "postgresql://localhost:5432/dots?schema=public",
  },
});
